# yaml-language-server: $schema=https://json.schemastore.org/yamllint.json

#Configuration
template: formal.html #Located in ./templates
use_photo: false
photo: photo.png
use_favicon: true
favicon: favicon.ico
pdf_generation: true
pdf_name: jane-doe.pdf

#Metadata
name: Jane Doe
title: Software Engineer
resume_link: disaa0.github.io/web-resume/
facts:
    - title: Residence
      url: https://maps.app.goo.gl/UCupEfpjguBUrz1D9
      icon: <i class="fa fa-home fact-icon"></i>
      text: New York
    - title: GitHub
      url: https://github.com/janedoe
      icon: <i class="fa-brands fa-github fact-icon"></i>
      text: jane_doe
    - title: LinkedIn
      url: https://www.linkedin.com/in/janedoe/
      icon: <i class="fa-brands fa-linkedin fact-icon"></i>
      text: jane_doe
    - title: Email
      url: mailto:janedoe@mail.com
      icon: <i class="fa fa-envelope fact-icon"></i>
      text: jane@mail.com

jobs:
  - position: Software Developer
    period: Jun 2020 - Present
    company: Tech Solutions Inc.
    bullet_points:
      - Developed and maintained web applications using Python and Django.
      - Collaborated with cross-functional teams to design, develop, and implement new features.
      - Implemented automated testing and continuous integration using Jenkins.
    technology:
      - Python
      - Django
      - Jenkins
  - position: Junior Developer
    period: Jan 2018 - May 2020
    company: CodeCraft
    bullet_points:
      - Assisted in the development of internal tools using JavaScript and Node.js.
      - Participated in code reviews and provided constructive feedback to peers.
      - Helped maintain code quality and organization.
    technology:
      - JavaScript
      - Node.js
      - Git

educations:
    - degree: Bachelor of Science in Computer Science
      period: Sep 2014 - Jun 2018
      university: University of Example
      projects: 
        # - title: Inventory Management System
        #   skills: ['MongoDB', 'Python', 'React']
        #   link: '<a href="https://github.com/user/repo"> <i class="fa-brands fa-github"></i> </a>'
        #   contents: 
        #     I developed an inventory management system for a local business, improving their inventory tracking and reporting capabilities.
        # - title: Personal Portfolio Website
        #   position: Developer
        #   period: Sep 2016 - Dec 2016
        #   skills: ['Python', 'Flask']
        #   link: '<a href="https://github.com/user/repo"><i class="fa-brands fa-github"></i></a>'
        #   contents:
        #     I developed my personal portfolio website, showcasing my projects and skills.
      relevant_courses: CS 101 - Introduction to CS, CS 201 - Data Structures and Algorithms, CS 301 - Computer Organization and Architecture.

personal_projects:
    - title: Personal Website
      period: January 2023 - Present
      description: A responsive website designed to present my work and projects. This website is built using HTML, CSS, and JavaScript, and is designed to be responsive and accessible on various devices.
      skills: ['HTML', 'CSS', 'JavaScript']
      link: '<a href="XXXXXXXXXXXXXXXXXXXXXXXXXXXX"><i class="fa-brands fa-github"></i></a>'

skills:
    - Strong problem-solving skills and ability to work in a team environment.
    - Eagerness to acquire new skills and knowledge.
    - Excellent communication and collaboration skills.
    - Experience in agile development methodologies.

tech_skills:
    - title: Programming Languages
      text: Python, Java, C++
    - title: Version Control
      text: Git, GitHub
    - title: Languages
      text: 'Spanish, English'